"""Add hosted Domain

Revision ID: 362d728ad7da
Revises: f73a96c97449
Create Date: 2025-08-11 16:38:48.891702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "362d728ad7da"
down_revision = "662d728ad7da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("docker_config", sa.Column("hostedDomain", sa.
                                             String(255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("docker_config", "hostedDomain")
    # ### end Alembic commands ###
